name: Periodic Workflow

on: 
  schedule:
    - cron: '5 * * * *'

jobs:
  information:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Imprimir nombre del workflow
        run: echo '${{ github.workflow }}'
      - name: Imprimir nombre de repositorio y propietario
        run: echo '${{ github.repository }}'
      - name: Imprimir sistema operativo donde se ejecuta el trabajo
        run: echo '${{ runner.os }}'
      - name: Imprimir URL al servidor de GitHub
        run: echo '${{ github.server_url }}'